GET https://localhost:7222/offers/2

###

POST https://localhost:7222/offers
Content-Type: application/json

    {
        "Description": "Best deal ever!!!"
    }

###

GET http://10.106.217.188:5000/offers/2

###

POST http://10.106.217.188:5000/offers
Content-Type: application/json

    {
        "Description": "Best deal ever!!!"
    }

